In [1]:
'''Problem: Create two NumPy arrays, A and B, of size 5x5 filled with random integers. Write a Python function to:

Find the element-wise sum of A and B.
Compute the dot product of A and B.
Calculate the mean and standard deviation of each row in A and B.'''

'Problem: Create two NumPy arrays, A and B, of size 5x5 filled with random integers. Write a Python function to:\n\nFind the element-wise sum of A and B.\nCompute the dot product of A and B.\nCalculate the mean and standard deviation of each row in A and B.'

In [2]:
import numpy as np

In [5]:
# create a numpy array A
A = np.random.randint(0, 10, size=(5, 5))
A

array([[7, 4, 8, 7, 1],
       [0, 6, 4, 1, 0],
       [0, 5, 8, 0, 6],
       [4, 3, 0, 0, 3],
       [5, 1, 6, 3, 4]])

In [6]:
# create a numpy array B
B = np.random.randint(0, 10, size=(5, 5))
B

array([[5, 8, 1, 5, 2],
       [3, 9, 3, 7, 0],
       [8, 1, 9, 6, 5],
       [5, 7, 8, 5, 6],
       [0, 3, 0, 7, 7]])

In [7]:
# Find the element-wise sum of A and B.
sum_result = np.add(A, B)
sum_result

array([[12, 12,  9, 12,  3],
       [ 3, 15,  7,  8,  0],
       [ 8,  6, 17,  6, 11],
       [ 9, 10,  8,  5,  9],
       [ 5,  4,  6, 10, 11]])

In [8]:
#Compute the dot product of A and B.
dot_product_result = np.dot(A, B)
dot_product_result

array([[146, 152, 147, 153, 103],
       [ 55,  65,  62,  71,  26],
       [ 79,  71,  87, 125,  82],
       [ 29,  68,  13,  62,  29],
       [ 91,  88,  86, 111,  86]])

In [11]:
#Calculate the mean and standard deviation of each row in A
mean_A = np.mean(A, axis=1)
mean_A

array([5.4, 2.2, 3.8, 2. , 3.8])

In [12]:
std_A = np.std(A, axis=1)
std_A

array([2.57681975, 2.4       , 3.24961536, 1.67332005, 1.72046505])

In [13]:
#Calculate the mean and standard deviation of each row in B
mean_B = np.mean(B,axis=1)
mean_B

array([4.2, 4.4, 5.8, 6.2, 3.4])

In [14]:
std_B = np.std(B,axis=1)
std_B

array([2.48193473, 3.2       , 2.78567766, 1.16619038, 3.13687743])